version: '3.9'

services:
  rawgraphs:
    container_name: rawgraphs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    stdin_open: true
    ports:
      - 3000:3000

