version: '3.9'

services:
  rawgraphs:
    container_name: rawgraphs
    image: node:14-alpine
    expose:
      - 3000
    volumes:
      - .:/app
    stdin_open: true
    ports:
      - 3000:3000
    working_dir: /app
    entrypoint: ["/bin/sh", "-c" ,"yarn install && yarn start --host 0.0.0.0"]

